services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contas
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/contas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: chaveJWT_tem_que_ter_pelo_menos_32_caracteres_pra_ser_considerada_valida_pelo_HMAC
      JWT_EXPIRATION_MS: 86400000
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs

volumes:
  db_data:
