spring:
  application:
    name: contasPagar
  mvc:
    async:
      request-timeout: 1800000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 50
      pool-name: db_contas_pool
      auto-commit: false
      connection-timeout: 30000
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/contas}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true
        generate_statistics: false
        boot:
          use_jdbc_metadata_defaults: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.lyncas.contas.contaspagar: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  override-with-generic-response: false

jwt:
  secret: "${JWT_SECRET:chaveJWT_tem_que_ter_pelo_menos_32_caractesres_pra_ser_valido_pelo_HMAC}"
  expiration.ms: "${JWT_EXPIRATION_MS:86400000}"
